# © 2022 Massachusetts Institute of Technology.  See LICENSE file for details.
globals:
  num_runs: 3
experiments:
  - time_max: 150
    pvs: [0.005, 0.01, 0.02, 0.04, 0.06]
    params: [0.05, 0.0025, 0.048, 0.064]
    num_comms: [6, 8, 10]
